import './globals.css';
import { Arvo, Source_Code_Pro } from 'next/font/google';
import clsx from 'clsx';

const arvo = Arvo({ weight: ['400', '700'], subsets: ['latin'] });
const sourceCodePro = Source_Code_Pro({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={clsx(arvo.className, sourceCodePro.className)}>{children}</body>
    </html>
  );
}
